/* ==========================================================================
   6c. SOM — tudo sintetizado, zero arquivos
   The game is a single HTML file and runs offline: there is no way to load an
   .mp3. So the audio follows the same idea as the sprites — it is generated by
   code. Each animal's voice
   comes from its BODY PLAN and its SIZE, the same way the drawing does, and a
   A PRNG seeded by the name gives each species a stable individuality.
   ========================================================================== */
/* A vocal gesture per family, with per-species exceptions where the animal
   its group's default (a zebra brays instead of whinnying; a fox barks instead of howling). */
const GESTURE_PLAN = {
  feline: 'roar', bear: 'growl', canine: 'howl', elephant: 'trumpet',
  giraffe: 'huff', equine: 'whinny', bovine: 'moo', ungulate: 'bleat',
  camelid: 'bleat', primate: 'call', bird: 'chirp', wader: 'chirp',
  penguin: 'squawk', snake: 'hiss', lizard: 'reptile', turtle: 'reptile',
  amphibian: 'croak', fish: 'whistle', seal: 'sealHuff', bat: 'squeak',
  insect: 'buzz', rodent: 'squeak', mustelid: 'squeak', swine: 'grunt',
  kangaroo: 'grunt', sloth: 'squeak', rhino: 'grunt', hippo: 'grunt',
};
/* Keyed by sp.key, which is the ENGLISH side of the species name — the same
   stable identity the sprite seed uses, so switching flags never changes a
   voice. Keying this by the Portuguese name silently matched nothing. */
const GESTURE_SPECIES = {
  'Plains zebra': 'bray', "Grévy's zebra": 'bray',
  'Red fox': 'bark', 'Arctic fox': 'bark', 'Fennec fox': 'bark',
  'African wild dog': 'bark', 'Dingo': 'bark', 'Coyote': 'howl', 'Dhole': 'bark',
  'Wildcat': 'meow', 'Ocelot': 'meow', 'Caracal': 'meow', 'Serval': 'meow',
  'Orca': 'whistle', 'Beluga': 'whistle', 'Walrus': 'sealHuff',
  'Meerkat': 'squeak', 'Coati': 'squeak', 'Red panda': 'squeak',
  'Ostrich': 'grunt', 'Rhea': 'grunt', 'Emu': 'grunt', 'Cassowary': 'grunt',
};
const gestureOf = sp => GESTURE_SPECIES[sp.key] || GESTURE_PLAN[sp.plan] ||
  (sp.scale > 1.2 ? 'grunt' : 'squeak');

const SFX = {
  ctx: null, master: null, far: null,
  on: true, vol: .65,
  _lastAt: new Map(),        // anti-spam, per event
  _active: 0,             // voices playing right now (the polyphony ceiling)
  _nextCritter: 0,

  /** The context can only be born in a user gesture (the autoplay policy). */
  start() {
    if (this.ctx) { if (this.ctx.state === 'suspended') this.ctx.resume(); return; }
    const AC = window.AudioContext || window.webkitAudioContext;
    if (!AC) return;
    try { this.ctx = new AC(); } catch (e) { return; }
    this.master = this.ctx.createGain();
    this.master.gain.value = this.on ? this.vol : 0;
    // a soft ceiling: stops clipping when many sounds land together
    const lim = this.ctx.createDynamicsCompressor();
    lim.threshold.value = -12; lim.knee.value = 12; lim.ratio.value = 6;
    this.master.connect(lim).connect(this.ctx.destination);
    this._ambiente();
  },
  applyVolume() {
    if (!this.ctx) return;
    const g = this.on ? this.vol : 0;
    this.master.gain.setTargetAtTime(g, this.ctx.currentTime, .05);
  },
  /** true if `name` can play right now (respecting the minimum interval) */
  _canPlay(name, msMin) {
    if (!this.ctx || !this.on) return false;
    if (this._active > 14) return false;
    const t = performance.now(), u = this._lastAt.get(name) || 0;
    if (t - u < (msMin || 45)) return false;
    this._lastAt.set(name, t);
    return true;
  },

  /* ---- synthesis blocks ---- */
  /** an oscillator with an envelope; f2 sweeps the frequency */
  _tone({ f = 440, f2, kind = 'sine', t = 0, dur = .18, vol = .3, atk = .006, vib, vibF = 6, dest, lp }) {
    const c = this.ctx, t0 = c.currentTime + t;
    const o = c.createOscillator(), g = c.createGain();
    o.type = kind;
    o.frequency.setValueAtTime(f, t0);
    if (f2) o.frequency.exponentialRampToValueAtTime(Math.max(1, f2), t0 + dur);
    if (vib) {  // vibrato: what gives a roar, a moo or a whinny some life
      const lfo = c.createOscillator(), lg = c.createGain();
      lfo.frequency.value = vibF; lg.gain.value = vib;
      lfo.connect(lg).connect(o.frequency); lfo.start(t0); lfo.stop(t0 + dur + .05);
    }
    g.gain.setValueAtTime(0, t0);
    g.gain.linearRampToValueAtTime(vol, t0 + atk);
    g.gain.exponentialRampToValueAtTime(.0001, t0 + dur);
    if (lp) {   // cuts the brightness: what separates "deep and low" from "generically harsh"
      const f = c.createBiquadFilter(); f.type = 'lowpass'; f.frequency.value = lp; f.Q.value = .7;
      o.connect(g).connect(f).connect(dest || this.master);
    } else o.connect(g).connect(dest || this.master);
    o.start(t0); o.stop(t0 + dur + .05);
    this._active++; o.onended = () => this._active--;
  },
  /** a burst of filtered noise: a thud, a brush, a hiss, a puff */
  _noise({ t = 0, dur = .18, vol = .3, kind = 'lowpass', f = 900, f2, Q = 1, dest, lp }) {
    const c = this.ctx, t0 = c.currentTime + t;
    const n = Math.max(1, Math.floor(c.sampleRate * dur));
    const buf = c.createBuffer(1, n, c.sampleRate);
    const d = buf.getChannelData(0);
    for (let i = 0; i < n; i++) d[i] = (Math.random() * 2 - 1);
    const src = c.createBufferSource(); src.buffer = buf;
    const bq = c.createBiquadFilter(); bq.type = kind; bq.Q.value = Q;
    bq.frequency.setValueAtTime(f, t0);
    if (f2) bq.frequency.exponentialRampToValueAtTime(Math.max(20, f2), t0 + dur);
    const g = c.createGain();
    g.gain.setValueAtTime(0, t0);
    g.gain.linearRampToValueAtTime(vol, t0 + .008);
    g.gain.exponentialRampToValueAtTime(.0001, t0 + dur);
    if (lp) {
      const fl = c.createBiquadFilter(); fl.type = 'lowpass'; fl.frequency.value = lp; fl.Q.value = .7;
      src.connect(bq).connect(g).connect(fl).connect(dest || this.master);
    } else src.connect(bq).connect(g).connect(dest || this.master);
    src.start(t0); src.stop(t0 + dur + .02);
    this._active++; src.onended = () => this._active--;
  },
  /** A vowel by formant synthesis, following Klatt (1980).
   *  Two things I had wrong and the literature corrects:
   *  1) A VOWEL IS A CASCADE. Resonators in series. Narrow band-passes in
   *     PARALLEL (my first attempt) isolate 3 bands and throw the rest away —
   *     it becomes a 3-tone chord. Klatt's parallel configuration exists for
   *     fricatives and plosives, not for vowels.
   *  2) THE SOURCE IS A PULSE TRAIN, band-limited, not a sawtooth. It is the
   *     source that carries the vocal quality; a sawtooth sounds electric.
   *  Formant frequencies: Peterson & Barney (1952), adult male.
   *  F4/F5 = 3500/4500 Hz, the usual values in synthesis. */
  _glottalWave() {
    if (this._glottis) return this._glottis;
    const n = 40, real = new Float32Array(n + 1), imag = new Float32Array(n + 1);
    // a ~12 dB/octave roll-off: the glottal pulse's profile (a sawtooth drops only 6)
    // Measured against a real voice: it concentrates 72–95% of its energy below
    // 1.5 kHz. A source rolling off at only -6 dB/octave leaves the top too
    // strong and the result sounds like a synthesiser. This is close to a real
    // glottal pulse (~-12).
    for (let k = 1; k <= n; k++) imag[k] = 1 / Math.pow(k, 1.6);
    return this._glottis = this.ctx.createPeriodicWave(real, imag);
  },
  _vowel({ f0 = 140, f0b, vowel = 'a', vowel2, dur = .3, vol = .22, t = 0, dest, kind = 'man' }) {
    const c = this.ctx, t0 = c.currentTime + t;
    const V = {  // Peterson & Barney (1952), homem adulto
      i: [270, 2290, 3010], e: [530, 1840, 2480], a: [730, 1090, 2440],
      o: [570, 840, 2410], u: [300, 870, 2240], ae: [660, 1720, 2410], er: [490, 1350, 1690],
    };
    const sizeF = kind === 'child' ? 1.35 : kind === 'woman' ? 1.17 : 1;
    const A = (V[vowel] || V.a).concat([3500, 4500]);
    const B = (V[vowel2] || V[vowel] || V.a).concat([3500, 4500]);
    const BW = [60, 90, 120, 150, 200];        // typical bandwidths
    const LOCUS = [250, 1750, 2600, 3400, 4400];  // ponto de partida no ataque

    // A syllable has a shape in time: a quick transition on the attack, then a
    // sustained target. A continuous ramp from start to end (what I had) shears
    // everything diagonally — that is a siren, not speech. A formant transition
    // takes ~60 ms (locus theory).
    const TRANS = Math.min(.06, dur * .3);
    const o = c.createOscillator();
    o.setPeriodicWave(this._glottalWave());
    o.frequency.setValueAtTime(f0, t0);
    o.frequency.setValueAtTime(f0, t0 + dur * .55);   // segura, depois entoa
    if (f0b) o.frequency.exponentialRampToValueAtTime(Math.max(40, f0b), t0 + dur);
    // jitter: a vocal fold is not an oscillator. Without this tremor the note is
    // straight and sounds like an organ. Keep it low (~0.3%): more than that and
    // it becomes operatic vibrato.
    [[5.7, 4], [12.9, 2]].forEach(([hz, cents]) => {
      const l = c.createOscillator(), lg = c.createGain();
      l.frequency.value = hz; l.type = 'sine'; lg.gain.value = cents;
      l.connect(lg).connect(o.detune); l.start(t0); l.stop(t0 + dur + .05);
    });

    // Aspiration: airflow that never becomes periodic. It is what fills the gap
    // between harmonics — compared with a real voice, without it the spectrum is
    // thin lines with black in between, which is the picture of a buzz, not a voice.
    const nn = Math.ceil(c.sampleRate * (dur + .05));
    const nb = c.createBuffer(1, nn, c.sampleRate), nd = nb.getChannelData(0);
    for (let i = 0; i < nn; i++) nd[i] = Math.random() * 2 - 1;
    const ns = c.createBufferSource(); ns.buffer = nb;
    const ng = c.createGain(); ng.gain.value = .05;
    const nlp = c.createBiquadFilter();   // above ~4 kHz a real voice is dark
    nlp.type = 'lowpass'; nlp.frequency.value = 2400; nlp.Q.value = .7;

    // the periodic source and the aspiration go through the SAME vocal tract
    const entrada = c.createGain();
    o.connect(entrada); ns.connect(ng).connect(nlp).connect(entrada);

    // a cascade of 5 resonators; Q = F/BW, as in the model
    let no = entrada;
    for (let i = 0; i < 5; i++) {
      const fA = A[i] * sizeF, fB = B[i] * sizeF;
      const r = c.createBiquadFilter();
      r.type = 'peaking';                       // boosts without throwing the rest away
      // The theoretical Q (F/BW) makes the formant narrower than the spacing
      // between harmonics — it falls in the gap and boosts nothing. Clamped, it
      // catches 2–3 harmonics.
      r.Q.value = Math.min(4.5, Math.max(1.8, fA / BW[i]));
      r.gain.value = [23, 19, 10, 4, 2][i];
      // the locus: where the formant starts on the attack (the consonant's place)
      r.frequency.setValueAtTime(fA + (LOCUS[i] - fA) * .55, t0);
      r.frequency.linearRampToValueAtTime(fA, t0 + TRANS);  // chega no alvo da vogal
      r.frequency.setValueAtTime(fA, t0 + dur * .55);       // e SEGURA
      if (vowel2) r.frequency.linearRampToValueAtTime(fB, t0 + dur);
      no = no.connect(r);
    }
    const mouth = c.createBiquadFilter();   // a vocal tract does not radiate the top freely
    mouth.type = 'lowpass'; mouth.frequency.value = 3400; mouth.Q.value = .5;

    const g = c.createGain();
    const vc = vol * .32;
    g.gain.setValueAtTime(0, t0);
    g.gain.linearRampToValueAtTime(vc, t0 + .035);
    g.gain.linearRampToValueAtTime(vc * .72, t0 + dur * .62);  // shimmer: the syllable decays
    g.gain.exponentialRampToValueAtTime(.0001, t0 + dur);
    no.connect(mouth).connect(g).connect(dest || this.master);
    o.start(t0); o.stop(t0 + dur + .05);
    ns.start(t0); ns.stop(t0 + dur + .05);
    this._active++; o.onended = () => this._active--;
  },

  /** A human voice: a visitor lets out a short interjection, a staff member
   *  answers in the manner of their role. Pitch and vowel come from the person's
   *  appearance, so
   *  o mesmo sujeito soa sempre igual. */
  humanVoice(p, opts) {
    if (!this.ctx || !this.on) return;
    const now = opts && opts.now;
    if (!now && !this._canPlay('humano', 200)) return;
    const r = mulberry(hashStr(personKey(p)) + 5);
    const child = !!p.child;
    // typical f0: man 100–130, woman 190–220, child 250–320
    const kind = child ? 'child' : (r() < .5 ? 'man' : 'woman');
    const f0 = child ? 250 + r() * 70 : kind === 'woman' ? 185 + r() * 45 : 100 + r() * 35;
    const vogais = ['a', 'e', 'i', 'o', 'u'];
    const vg = vogais[(r() * vogais.length) | 0];
    const v = (opts && opts.vol) || .22;
    const dest = (opts && opts.distant) ? this.far : undefined;

    if (p.role === 'keeper') {            // tratador assobia, como quem chama bicho
      this._tone({ f: 1250, f2: 1850, kind: 'sine', dur: .16, vol: v * .5, dest });
      this._tone({ f: 1850, f2: 1400, kind: 'sine', dur: .2, vol: v * .45, t: .15, dest });
      return;
    }
    if (p.role === 'cleaner') {             // faxineiro suspira
      this._noise({ dur: .45, vol: v * .3, kind: 'bandpass', f: 900, f2: 500, Q: .8, lp: 1600, dest });
      this._vowel({ f0, f0b: f0 * .82, vowel: 'u', dur: .4, vol: v * .5, kind, dest });
      return;
    }
    if (p.role) {                        // vet / security: two firm syllables
      this._vowel({ f0: f0 * .95, vowel: 'o', vowel2: 'i', dur: .17, vol: v * .8, kind, dest });
      this._vowel({ f0: f0 * .85, f0b: f0 * .7, vowel: 'a', vowel2: 'e', dur: .27, vol: v * .75, t: .18, kind, dest });
      return;
    }
    // visitor: a one-syllable interjection, with intonation (rising = a question)
    const sobe = r() < .5;
    const vg2 = vogais[(r() * vogais.length) | 0];
    this._vowel({ f0, f0b: sobe ? f0 * 1.28 : f0 * .78, vowel: vg, vowel2: vg2,
                  dur: .26 + r() * .12, vol: v, kind, dest });
    if (r() < .35)                       // sometimes a second syllable
      this._vowel({ f0: f0 * .92, f0b: f0 * .75, vowel: vogais[(r() * 5) | 0],
                    dur: .24, vol: v * .8, t: .3, kind, dest });
  },

  _chord(freqs, { kind = 'sine', dur = .3, vol = .16, step = .07 } = {}) {
    freqs.forEach((f, i) => this._tone({ f, kind, dur, vol, t: i * step }));
  },

  /* ---- game events ---- */
  play(name) {
    switch (name) {
      case 'ui':        if (!this._canPlay(name, 35)) return; this._tone({ f: 880, f2: 1180, dur: .05, vol: .12 }); break;
      case 'tab':       if (!this._canPlay(name, 60)) return; this._tone({ f: 520, f2: 780, dur: .09, vol: .14, kind: 'triangle' }); break;
      case 'open':     if (!this._canPlay(name, 80)) return; this._chord([440, 660], { dur: .16, vol: .1, step: .04 }); break;
      case 'close':    if (!this._canPlay(name, 80)) return; this._chord([660, 440], { dur: .14, vol: .09, step: .04 }); break;
      case 'error':      if (!this._canPlay(name, 180)) return; this._tone({ f: 190, f2: 110, kind: 'square', dur: .17, vol: .16 }); break;
      case 'path':    if (!this._canPlay(name, 55)) return; this._noise({ dur: .07, vol: .16, f: 1600, f2: 500 }); break;
      case 'terrain':   if (!this._canPlay(name, 55)) return; this._noise({ dur: .1, vol: .1, kind: 'bandpass', f: 700, f2: 1500, Q: .7 }); break;
      case 'building':    if (!this._canPlay(name, 90)) return;
        this._noise({ dur: .16, vol: .22, f: 700, f2: 160 }); this._tone({ f: 150, f2: 80, kind: 'triangle', dur: .2, vol: .16 }); break;
      case 'construct': if (!this._canPlay(name, 120)) return;
        this._noise({ dur: .22, vol: .2, f: 1200, f2: 260 });
        this._chord([330, 440, 550], { kind: 'triangle', dur: .28, vol: .12, step: .06 }); break;
      case 'extend':   if (!this._canPlay(name, 120)) return;
        this._noise({ dur: .16, vol: .16, f: 900, f2: 300 });
        this._chord([392, 523], { kind: 'triangle', dur: .24, vol: .12, step: .07 }); break;
      case 'demolish':   if (!this._canPlay(name, 90)) return;
        this._noise({ dur: .3, vol: .26, f: 1800, f2: 120, Q: .6 }); this._tone({ f: 110, f2: 55, kind: 'square', dur: .18, vol: .1 }); break;
      case 'coin':     if (!this._canPlay(name, 70)) return;
        this._tone({ f: 1180, dur: .07, vol: .1 }); this._tone({ f: 1560, dur: .1, vol: .09, t: .05 }); break;
      case 'buy':    if (!this._canPlay(name, 150)) return;
        this._tone({ f: 880, dur: .08, vol: .13 }); this._tone({ f: 1320, dur: .1, vol: .12, t: .07 });
        this._tone({ f: 1760, dur: .16, vol: .1, t: .14 }); break;
      case 'birth': if (!this._canPlay(name, 400)) return;
        this._chord([523, 659, 784, 1046], { kind: 'triangle', dur: .3, vol: .13, step: .09 }); break;
      case 'death':     if (!this._canPlay(name, 400)) return;
        this._chord([392, 330, 262], { kind: 'sine', dur: .5, vol: .13, step: .16 }); break;
      case 'sick':    if (!this._canPlay(name, 400)) return;
        this._tone({ f: 420, f2: 300, kind: 'triangle', dur: .35, vol: .12, vib: 22, vibF: 9 }); break;
      case 'alarm':    if (!this._canPlay(name, 700)) return;
        for (let i = 0; i < 3; i++) {
          this._tone({ f: 780, kind: 'square', dur: .13, vol: .12, t: i * .22 });
          this._tone({ f: 560, kind: 'square', dur: .13, vol: .12, t: i * .22 + .11 });
        } break;
      case 'day':       if (!this._canPlay(name, 900)) return;
        this._chord([523, 784, 1046], { kind: 'sine', dur: .8, vol: .1, step: .11 }); break;
      case 'bills':    if (!this._canPlay(name, 900)) return;
        this._noise({ dur: .3, vol: .12, kind: 'highpass', f: 2600 });
        this._tone({ f: 300, f2: 180, kind: 'triangle', dur: .3, vol: .12, t: .1 }); break;
      case 'bankrupt':  if (!this._canPlay(name, 2000)) return;
        this._chord([330, 262, 196, 131], { kind: 'sawtooth', dur: .9, vol: .12, step: .22 }); break;
    }
  },

  /* ==========================================================================
     VOICES — one "vocal gesture" per family, with per-species exceptions.
     Size (sizeF) pulls the pitch down and the PRNG seeded by the name gives a
     stable detuning, so two species sharing a gesture never sound alike.
     ========================================================================== */
  animalVoice(sp, opts) {
    const wait = (opts && opts.now) ? 0 : 240;
    if (wait && !this._canPlay('voz' + sp.id, wait)) return;
    if (!this.ctx || !this.on) return;
    const dest = (opts && opts.distant) ? this.far : undefined;
    const _t = this._tone, _r = this._noise;
    this._tone = o => _t.call(this, { ...o, dest });
    this._noise = o => _r.call(this, { ...o, dest });
    try {
      const r = mulberry(hashStr(sp.key) + 11);
      const grave = 1 / (.45 + Math.min(sp.scale, 2.3) * .78);   // maior = mais grave
      const dt = 1 + (r() - .5) * .16;                          // a timbre of its own
      const F = f => Math.max(30, f * grave * dt);
      const v = (opts && opts.vol) || .22;
      (this['_g_' + gestureOf(sp)] || this._g_grunt).call(this, F, v, r, sp);
    } finally { this._tone = _t; this._noise = _r; }
  },

  /* ---- gestos ---- */
  _g_roar(F, v, r) {         // lion, tiger, jaguar
    // A real roar is NOT a continuous buzz: it is a sequence of pulsed groans,
    // each with its own attack and a long decay, separated by silence. That was
    // what was missing — I had the frequency range right and the shape wrong, and
    // shape is what the ear uses to recognise the animal.
    const f0 = F(140), n = 2 + (r() * 2 | 0);
    let t = 0;
    for (let i = 0; i < n; i++) {
      const last = i === n - 1;
      const dur = last ? .85 : .38 + r() * .12;        // the last groan is the long one
      const k = 1 + (r() - .5) * .12;                  // cada pulso desafina um tico
      [[1, 1], [2, .55], [3, .3], [4, .14]].forEach(([m, g]) =>
        this._tone({ f: f0 * m * k, f2: f0 * m * k * (last ? .6 : .82), kind: 'sawtooth',
                    t, dur, vol: v * g * (last ? .62 : .5), atk: .06,
                    vib: f0 * m * .06, vibF: 26 + r() * 8, lp: F(1700) }));
      this._noise({ t, dur, vol: v * .16, kind: 'bandpass',
                    f: F(600), f2: F(230), Q: .8, lp: F(1400) });
      t += dur + .1 + r() * .07;                       // the silence between groans
    }
  },
  _g_meow(F, v) {            // small cat
    this._tone({ f: F(620), f2: F(880), kind: 'sawtooth', dur: .18, vol: v * .8, atk: .03, vib: 24, vibF: 12 });
    this._tone({ f: F(880), f2: F(520), kind: 'sawtooth', dur: .3, vol: v * .7, t: .16, vib: 20, vibF: 10 });
  },
  _g_growl(F, v) {           // bear: ragged, and more MIDRANGE than it seems
    // Measured against a real recording: a bear's growl concentrates ~89% of its
    // energy between 500 and 1500 Hz. "Big animal = sub-bass" is a wrong hunch.
    const f0 = F(420);
    [[1, .22], [2, 1], [3, .9], [4, .5], [5, .25]].forEach(([m, g]) =>
      this._tone({ f: f0 * m, f2: f0 * m * .8, kind: 'sawtooth', dur: .8, vol: v * g * .5,
                  atk: .1, vib: f0 * m * .09, vibF: 19, lp: F(3000) }));
    this._noise({ dur: .8, vol: v * .18, kind: 'bandpass', f: F(900), f2: F(500), Q: .9, lp: F(2400) });
  },
  _g_howl(F, v) {            // wolf: rises, holds, falls
    // A real howl is tonal but NOT a sine: it has a dense harmonic stack.
    // A triangle/sine (what I used) comes out too thin and sounds like a whistle.
    const a = F(360), b = F(600), lp = F(3000);
    const trecho = (f1, f2, t, dur, vol, vib, vibF) =>
      [[1, 1], [2, .5], [3, .28], [4, .15]].forEach(([m, g]) =>
        this._tone({ f: f1 * m, f2: f2 * m, kind: 'sawtooth', t, dur, vol: vol * g,
                    atk: .06, vib: vib * m, vibF, lp }));
    trecho(a, b, 0, .45, v * .5, 7, 5);       // sobe
    trecho(b, b, .43, .55, v * .48, 9, 5.5);  // sustenta
    trecho(b, a * .75, .96, .75, v * .42, 12, 6);  // desce
    this._noise({ dur: 1.7, vol: v * .13, kind: 'bandpass', f: b, f2: a, Q: .9, lp: F(2600) });  // sopro
  },
  _g_bark(F, v, r) {         // fox, wild dog: short bursts
    for (let i = 0; i < 2 + (r() * 2 | 0); i++) {
      this._tone({ f: F(520), f2: F(300), kind: 'sawtooth', dur: .1, vol: v * .9, t: i * .19, atk: .008, vib: 28, vibF: 20 });
      this._noise({ dur: .08, vol: v * .5, kind: 'bandpass', f: 1300, f2: 500, Q: 1, t: i * .19 });
    }
  },
  _g_trumpet(F, v) {         // elephant: metallic, rises and falls, with a rumble under it
    // The real thing has 34% of its energy above 1.5 kHz — a trumpet is metallic, not a rumble.
    this._tone({ f: F(520), f2: F(1150), kind: 'sawtooth', dur: .22, vol: v * 1.1, atk: .02, vib: 16, vibF: 13, lp: 6000 });
    this._tone({ f: F(1150), f2: F(640), kind: 'sawtooth', dur: .5, vol: v, t: .2, vib: 26, vibF: 10, lp: 6000 });
    this._noise({ t: .04, dur: .55, vol: v * .75, kind: 'bandpass', f: F(4000), f2: F(2600), Q: .7 });  // a metallic blast
    this._tone({ f: F(78), dur: .85, vol: v * .45, kind: 'sine', atk: .05 });   // the rumble that gives it its size
  },
  _g_huff(F, v) {            // giraffe and okapi: a huff + a low hum
    // A giraffe is a near-silent animal: it snorts, it huffs and it emits a ~92 Hz
    // hum. No roar — the "right" answer here is to be discreet.
    this._noise({ dur: .38, vol: v * .8, kind: 'bandpass', f: 1100, f2: 300, Q: .6, lp: 1800 });
    this._tone({ f: F(150), f2: F(96), kind: 'triangle', dur: .34, vol: v * .5, atk: .02, lp: 700 });
    this._tone({ f: 92, dur: 1.3, vol: v * .7, kind: 'sine', atk: .18, t: .16 });  // 92 Hz is a fact about the animal
  },
  _g_bray(F, v) {            // zebra: a two-part bark
    for (let i = 0; i < 2; i++) {
      this._tone({ f: F(430), f2: F(230), kind: 'sawtooth', dur: .17, vol: v, t: i * .28, atk: .01, vib: 34, vibF: 17 });
      this._noise({ dur: .13, vol: v * .4, kind: 'bandpass', f: 800, f2: 340, Q: 1, t: i * .28, lp: 1900 });
    }
  },
  _g_whinny(F, v) {          // horse, donkey
    // real: 57% between 1.5 and 3 kHz — a whinny is shrill
    this._tone({ f: F(3100), f2: F(1500), kind: 'sawtooth', dur: .7, vol: v * .8, atk: .02, vib: 60, vibF: 16 });
    this._tone({ f: F(420), f2: F(300), kind: 'sawtooth', dur: .5, vol: v * .22, atk: .04, t: .3, lp: F(900) });
    this._noise({ dur: .3, vol: v * .4, kind: 'bandpass', f: 2400, f2: 1100, Q: .8, t: .5 });
  },
  _g_moo(F, v) {             // bovine: long, low, a slow undulation
    // real: 77% between 500 and 1500 Hz. A moo is sustained, not sub-bass.
    this._tone({ f: F(430), f2: F(360), kind: 'sawtooth', dur: .95, vol: v * .3, atk: .15, vib: 12, vibF: 5.5, lp: F(2600) });
    this._tone({ f: F(860), f2: F(720), kind: 'sawtooth', dur: .9, vol: v * .9, atk: .18, vib: 14, vibF: 5.5, lp: F(2600) });
  },
  _g_bleat(F, v) {           // antelope, camelid: the fast vibrato of a goat
    // real: 52% between 1.5 and 3 kHz; the fast vibrato is the signature
    this._tone({ f: F(2500), f2: F(2050), kind: 'sawtooth', dur: .55, vol: v * .7, atk: .04, vib: 130, vibF: 21 });
    this._tone({ f: F(700), f2: F(600), kind: 'sawtooth', dur: .5, vol: v * .3, atk: .05, vib: 50, vibF: 21, lp: F(1100) });
  },
  _g_call(F, v, r) {         // primate: a pant-hoot that speeds up and rises
    const n = 4 + (r() * 3 | 0);
    for (let i = 0; i < n; i++) {
      const k = i / n;
      // a real chimpanzee pant-hoot: 61% of its energy below 500 Hz
      this._tone({ f: F(175 + k * 190), f2: F(230 + k * 240), kind: 'sawtooth',
                  dur: .12, vol: v * (.5 + k * .5), t: i * (.17 - k * .07), atk: .01, lp: F(1600) });
      this._noise({ t: i * (.17 - k * .07), dur: .12, vol: v * .17, kind: 'bandpass',
                    f: F(700), Q: .8, lp: F(2200) });   // ar do arquejo
    }
  },
  _g_chirp(F, v, r) {        // birds: short, high sweeps
    for (let i = 0; i < 3 + (r() * 3 | 0); i++) {
      const f = F(1900 + r() * 1100);
      this._tone({ f, f2: f * (1.4 + r() * .6), kind: 'sine', dur: .06, vol: v * .55, t: i * .095, atk: .004 });
      this._tone({ f: f * .45, f2: f * .6, kind: 'triangle', dur: .06, vol: v * .3, t: i * .095, atk: .004 });
    }
  },
  _g_squawk(F, v) {          // penguin, goose: harsh pulses
    for (let i = 0; i < 3; i++)
      // real: 73% between 1.5 and 3 kHz — a squawk is harsh and high
      this._tone({ f: F(1750), f2: F(1350), kind: 'sawtooth', dur: .17, vol: v * .7, t: i * .21, vib: 45, vibF: 25, lp: F(2900) });
  },
  _g_hiss(F, v) {            // snake
    this._noise({ dur: .8, vol: v * .8, kind: 'highpass', f: 3600, f2: 6800, Q: .5 });
  },
  _g_reptile(F, v) {         // lizard, crocodile, tortoise: a puff + a rumble
    this._noise({ dur: .5, vol: v * .55, kind: 'bandpass', f: F(760), f2: F(300), Q: 1.3 });
    this._tone({ f: F(105), f2: F(72), kind: 'sawtooth', dur: .45, vol: v * .6, vib: 9, vibF: 13 });
  },
  _g_croak(F, v, r) {        // amphibian: dry pulses
    const n = 4 + (r() * 3 | 0);
    for (let i = 0; i < n; i++) {   // real: ~92% da energia entre 1,5 e 3 kHz
      this._tone({ f: F(1350), kind: 'square', dur: .055, vol: v * .35, t: i * .08, atk: .004, lp: F(3600) });
      this._noise({ t: i * .08, dur: .05, vol: v * .5, kind: 'bandpass', f: F(2200), Q: 2.2, lp: F(2900) });
    }
  },
  _g_whistle(F, v) {         // dolphin, river dolphin
    this._tone({ f: F(1600), f2: F(2700), kind: 'sine', dur: .15, vol: v * .5, atk: .01 });
    this._tone({ f: F(2600), f2: F(1300), kind: 'sine', dur: .22, vol: v * .45, t: .14 });
    this._tone({ f: F(900), f2: F(1250), kind: 'sine', dur: .34, vol: v * .55, atk: .02 });  // corpo
    this._noise({ dur: .34, vol: v * .12, kind: 'bandpass', f: F(1800), Q: .8, lp: F(3400) });  // sopro
    for (let i = 0; i < 5; i++)  // echolocation clicks
      this._tone({ f: 5200, dur: .012, vol: v * .18, t: .36 + i * .035 });
  },
  _g_sealHuff(F, v) {        // seal, sea lion
    for (let i = 0; i < 2; i++)
      this._tone({ f: F(330), f2: F(210), kind: 'sawtooth', dur: .21, vol: v * .85, t: i * .28, vib: 22, vibF: 15 });
  },
  _g_squeak(F, v, r) {       // rodent, bat, the small ones: high and short
    for (let i = 0; i < 2 + (r() * 2 | 0); i++) {
      const f = F(1500 + r() * 700);
      this._tone({ f, f2: f * .6, kind: 'triangle', dur: .08, vol: v * .5, t: i * .11, atk: .005 });
    }
  },
  _g_buzz(F, v) {         // invertebrados
    this._noise({ dur: .5, vol: v * .35, kind: 'bandpass', f: 4200, Q: 9 });
  },
  _g_grunt(F, v, r) {        // pig, hippo, rhino and the big generics
    const n = 3 + (r() * 2 | 0);
    for (let i = 0; i < n; i++) {
      this._tone({ f: F(560), f2: F(390), kind: 'square', dur: .1, vol: v * .3, t: i * .13, atk: .008 });
      this._noise({ t: i * .13, dur: .09, vol: v * 1.0, kind: 'bandpass', f: F(2600), Q: .7 });
    }
  },

  /* ---- the "distant" bus ----
     Background animal voices go through here and come out muffled, as if from
     the other side of the park. (The crowd murmur was dropped: noise with
     formants still sounds like wind, not conversation — convincing speech needs
     glottal excitation and a pitch contour, and that is for another day.) */
  _ambiente() {
    const c = this.ctx;
    this.far = c.createGain(); this.far.gain.value = .5;
    const lp = c.createBiquadFilter();
    lp.type = 'lowpass'; lp.frequency.value = 1200; lp.Q.value = .6;
    this.far.connect(lp).connect(this.master);
  },
};