// As 10 fases da campanha do Brasil.
//
// Cada uma muda três coisas ao mesmo tempo: o cenário (paleta e elementos),
// uma regra de tabuleiro (água, névoa, noite, seca) e o elenco de monstros.
// A dificuldade sobe pelas três, não só pelo número de inimigos.
//
// onda: { espera: segundos depois da onda anterior, monstros: [[id, quantos]] }

export const CAMPANHA = {
  pais: 'Brasil',
  bandeira: '🇧🇷',
  populacao: 215,
  chamada: 'A resistência começa aqui.',
};

export const FASES = [
  {
    n: 1,
    nome: 'Sítio do Interior',
    local: 'Minas Gerais',
    intro: 'Um sítio de porteira aberta e ninguém para fechar. O primeiro lugar que os bichos escolheram retomar.',
    cenario: 'mata',
    humanos: 2,
    moedas: 150,
    sementesIniciais: 100,
    novidade: {
      aviso: 'Semente vem de dois lugares: o Esquilo produz e deixa cair no chão — você clica para pegar — e todo monstro derrubado devolve semente sozinho. Quanto mais rápido você mata, mais rico fica.',
    },
    ondas: [
      { espera: 12, monstros: [['corposeco', 1]] },
      { espera: 22, monstros: [['corposeco', 2]] },
      { espera: 24, monstros: [['corposeco', 3]] },
      { espera: 26, monstros: [['corposeco', 4]] },
    ],
  },
  {
    n: 2,
    nome: 'Mata Atlântica',
    local: 'Serra do Mar',
    intro: 'Mata fechada, cipó no pé e um assobio que vem sempre da direção errada.',
    cenario: 'mata',
    humanos: 5,
    moedas: 170,
    sementesIniciais: 100,
    novidade: { monstro: 'saci', aviso: 'O Saci pula por cima da primeira defesa. Não adianta uma parede só.' },
    ondas: [
      { espera: 10, monstros: [['corposeco', 2]] },
      { espera: 20, monstros: [['saci', 1], ['corposeco', 2]] },
      { espera: 22, monstros: [['saci', 2], ['corposeco', 3]] },
      { espera: 24, monstros: [['saci', 3], ['corposeco', 4]] },
      { espera: 26, monstros: [['saci', 4], ['corposeco', 5]] },
    ],
  },
  {
    n: 3,
    nome: 'Cerrado',
    local: 'Chapada dos Veadeiros',
    intro: 'Capim alto até a cintura e árvore torta que não faz sombra para ninguém.',
    cenario: 'cerrado',
    humanos: 8,
    moedas: 200,
    sementesIniciais: 100,
    novidade: { monstro: 'curupira', aviso: 'O Curupira corre com os pés virados. Chega antes do que você calculou.' },
    ondas: [
      { espera: 10, monstros: [['corposeco', 3]] },
      { espera: 18, monstros: [['curupira', 2], ['saci', 1]] },
      { espera: 20, monstros: [['cabecadecuia', 1], ['corposeco', 3]] },
      { espera: 22, monstros: [['curupira', 3], ['cabecadecuia', 2]] },
      { espera: 24, monstros: [['curupira', 4], ['saci', 3], ['corposeco', 4]] },
    ],
  },
  {
    n: 4,
    nome: 'Pantanal',
    local: 'Mato Grosso do Sul',
    intro: 'Metade chão, metade água, e nunca a metade que você queria.',
    cenario: 'pantanal',
    agua: [1, 3],
    humanos: 12,
    moedas: 230,
    sementesIniciais: 125,
    novidade: { monstro: 'iara', aviso: 'Fileira alagada só aceita bicho aquático. E a Iara flutua: só quem alcança o alto acerta nela.' },
    ondas: [
      { espera: 12, monstros: [['corposeco', 3]] },
      { espera: 18, monstros: [['iara', 1], ['curupira', 2]] },
      { espera: 20, monstros: [['cabecadecuia', 2], ['saci', 2]] },
      { espera: 22, monstros: [['iara', 3], ['corposeco', 4]] },
      { espera: 24, monstros: [['iara', 3], ['curupira', 3], ['cabecadecuia', 2]] },
    ],
  },
  {
    n: 5,
    nome: 'Caatinga',
    local: 'Sertão da Bahia',
    intro: 'Terra rachada, sol de meio-dia o dia todo. Aqui até semente pensa duas vezes antes de brotar.',
    cenario: 'caatinga',
    // a seca corta a renda passiva, não a de combate: aqui o jogo empurra para
    // matar rápido em vez de só plantar gerador e esperar
    fatorSementes: 0.72,
    humanos: 18,
    moedas: 270,
    sementesIniciais: 175,
    chefinho: 'mapinguari',
    novidade: { monstro: 'mula', aviso: 'A seca corta sua produção de sementes. E a Mula sem Cabeça usa armadura — tiro fraco quica nela.' },
    ondas: [
      { espera: 12, monstros: [['corposeco', 4]] },
      { espera: 18, monstros: [['mula', 1], ['curupira', 2]] },
      { espera: 20, monstros: [['mula', 2], ['cabecadecuia', 2]] },
      { espera: 22, monstros: [['mula', 2], ['saci', 3], ['curupira', 3]] },
      { espera: 26, monstros: [['mapinguari', 1], ['mula', 2], ['corposeco', 5]] },
    ],
  },
  {
    n: 6,
    nome: 'Amazônia',
    local: 'Rio Negro',
    intro: 'A névoa entra pela mata e engole o caminho. Some tudo: a trilha, o rio e o que vem vindo.',
    cenario: 'amazonia',
    nevoa: true,
    agua: [4],
    humanos: 25,
    moedas: 310,
    sementesIniciais: 150,
    novidade: { monstro: 'boitata', aviso: 'A névoa esconde o meio do campo. Uma Coruja na fileira levanta o véu. E o Boitatá queima de longe.' },
    ondas: [
      { espera: 12, monstros: [['corposeco', 4]] },
      { espera: 18, monstros: [['boitata', 1], ['curupira', 3]] },
      { espera: 20, monstros: [['boitata', 2], ['iara', 2]] },
      { espera: 22, monstros: [['mula', 2], ['boitata', 2], ['saci', 3]] },
      { espera: 26, monstros: [['boitata', 3], ['mapinguari', 1], ['curupira', 4]] },
    ],
  },
  {
    n: 7,
    nome: 'Litoral do Nordeste',
    local: 'Praia de Pernambuco',
    intro: 'Maré cheia e lua nova. No escuro, uma coisa velha lembra que era medo de criança.',
    cenario: 'praia',
    noite: true,
    agua: [0, 4],
    humanos: 30,
    moedas: 360,
    sementesIniciais: 175,
    chefinho: 'bichopapao',
    novidade: { monstro: 'bichopapao', aviso: 'No escuro o Bicho-papão anda invisível. Sem alguém que enxergue à noite, você só percebe quando ele morde.' },
    ondas: [
      { espera: 12, monstros: [['corposeco', 4], ['iara', 2]] },
      { espera: 18, monstros: [['boitata', 2], ['mula', 2]] },
      { espera: 20, monstros: [['iara', 4], ['cabecadecuia', 3]] },
      { espera: 22, monstros: [['curupira', 5], ['saci', 4]] },
      { espera: 28, monstros: [['bichopapao', 1], ['mula', 3], ['boitata', 2]] },
    ],
  },
  {
    n: 8,
    nome: 'Centro de São Paulo',
    local: 'Vale do Anhangabaú',
    intro: 'Vinte milhões de pessoas paradas onde estavam. O silêncio aqui é mais alto que em qualquer mata.',
    cenario: 'cidade',
    humanos: 40,
    moedas: 410,
    sementesIniciais: 200,
    novidade: { monstro: 'lobisomem', aviso: 'Cidade grande, horda grande. E o Lobisomem fica mais rápido quanto mais apanha.' },
    ondas: [
      { espera: 10, monstros: [['corposeco', 6]] },
      { espera: 16, monstros: [['lobisomem', 2], ['curupira', 4]] },
      { espera: 18, monstros: [['lobisomem', 3], ['mula', 3]] },
      { espera: 20, monstros: [['boitata', 3], ['saci', 5], ['cabecadecuia', 3]] },
      { espera: 22, monstros: [['lobisomem', 4], ['mapinguari', 2], ['corposeco', 8]] },
    ],
  },
  {
    n: 9,
    nome: 'Serra da Mantiqueira',
    local: 'Divisa de Minas',
    intro: 'A última subida antes do mar. Se eles descerem daqui, chegam ao Rio antes de você.',
    cenario: 'serra',
    nevoa: true,
    humanos: 45,
    moedas: 470,
    sementesIniciais: 200,
    novidade: { monstro: 'mapinguari', aviso: 'Névoa de novo, e agora o Mapinguari vem em bando. Ele aguenta mais pancada que qualquer coisa que você viu.' },
    ondas: [
      { espera: 10, monstros: [['mula', 3], ['curupira', 4]] },
      { espera: 16, monstros: [['mapinguari', 2], ['boitata', 3]] },
      { espera: 18, monstros: [['lobisomem', 4], ['iara', 4]] },
      { espera: 20, monstros: [['mapinguari', 3], ['saci', 5], ['cabecadecuia', 4]] },
      { espera: 24, monstros: [['mapinguari', 4], ['lobisomem', 5], ['mula', 4]] },
    ],
  },
  {
    n: 10,
    nome: 'Cristo Redentor',
    local: 'Rio de Janeiro',
    intro: 'Do alto do Corcovado dá para ver o país inteiro esperando. Ela está sentada lá em cima, e faz sete anos que espera por isto.',
    cenario: 'cristo',
    noite: true,
    humanos: 30,
    moedas: 600,
    sementesIniciais: 250,
    chefe: 'cuca',
    novidade: { monstro: 'cuca', aviso: 'A Cuca não vem sozinha e não vem depressa. Ela chama reforço enquanto anda — e quanto mais apanha, mais brava fica.' },
    ondas: [
      { espera: 10, monstros: [['corposeco', 6], ['curupira', 4]] },
      { espera: 16, monstros: [['mula', 4], ['boitata', 3]] },
      { espera: 18, monstros: [['lobisomem', 4], ['mapinguari', 2]] },
      { espera: 22, monstros: [['cuca', 1]] },
      { espera: 30, monstros: [['mapinguari', 3], ['lobisomem', 4], ['mula', 4]] },
    ],
  },
];

/** Total de humanos que a campanha do Brasil devolve (em milhões). */
export const HUMANOS_BRASIL = FASES.reduce((s, f) => s + f.humanos, 0);
