/* The audio engine as it was BEFORE the formant rewrite. before-after.html
   loads it beside the current one and renders both, so you can hear what the
   change did.

   Only the names were translated — every constant, every filter and every
   envelope is untouched, so the "before" still renders the same samples. The
   gesture table had to follow the species' body plans to English too, or this
   engine would fall through to its generic voice for all 219 of them. */

/* ==========================================================================
   6c. SOM — tudo sintetizado, zero arquivos
   The game is a single HTML file and runs offline: there is no way to load an
   .mp3. So the audio follows the same idea as the sprites — it is generated by
   code. Each animal's voice
   comes from its BODY PLAN and its SIZE, the same way the drawing does, and a
   A PRNG seeded by the name gives each species a stable individuality.
   ========================================================================== */
/* A vocal gesture per family, with per-species exceptions where the animal
   breaks its group's default (a zebra brays instead of whinnying; a fox barks
   instead of howling). */
const GESTURE_PLAN = {
  feline: 'roar', bear: 'growl', canine: 'howl', elephant: 'trumpet',
  giraffe: 'huff', equine: 'whinny', bovine: 'moo', ungulate: 'bleat',
  camelid: 'bleat', primate: 'call', bird: 'chirp', wader: 'chirp',
  penguin: 'squawk', snake: 'hiss', lizard: 'reptile', turtle: 'reptile',
  amphibian: 'croak', fish: 'whistle', seal: 'sealHuff', bat: 'squeak',
  insect: 'buzz', rodent: 'squeak', mustelid: 'squeak', swine: 'grunt',
  kangaroo: 'grunt', sloth: 'squeak', rhino: 'grunt', hippo: 'grunt',
};
/* keyed the way sp.key is keyed today: the English side */
const GESTURE_SPECIES = {
  'Plains zebra': 'bray', "Grévy's zebra": 'bray',
  'Red fox': 'bark', 'Arctic fox': 'bark', 'Fennec fox': 'bark',
  'African wild dog': 'bark', 'Dingo': 'bark', 'Coyote': 'howl', 'Dhole': 'bark',
  'Wildcat': 'meow', 'Ocelot': 'meow', 'Caracal': 'meow', 'Serval': 'meow',
  'Orca': 'whistle', 'Beluga': 'whistle', 'Walrus': 'sealHuff',
  'Meerkat': 'squeak', 'Coati': 'squeak', 'Red panda': 'squeak',
  'Ostrich': 'grunt', 'Rhea': 'grunt', 'Emu': 'grunt', 'Cassowary': 'grunt',
};
const gestureOf = sp => GESTURE_SPECIES[sp.key] || GESTURE_PLAN[sp.plano] ||
  (sp.sizeF > 1.2 ? 'grunt' : 'squeak');

const SFX = {
  ctx: null, master: null, multidao: null, noite: null,
  on: true, vol: .65,
  _lastAt: new Map(),        // antisspam por evento
  _active: 0,             // voices playing right now (the polyphony ceiling)
  _proxBicho: 0,

  /** The context can only be born in a user gesture (the autoplay policy). */
  start() {
    if (this.ctx) { if (this.ctx.state === 'suspended') this.ctx.resume(); return; }
    const AC = window.AudioContext || window.webkitAudioContext;
    if (!AC) return;
    try { this.ctx = new AC(); } catch (e) { return; }
    this.master = this.ctx.createGain();
    this.master.gain.value = this.on ? this.vol : 0;
    // a soft ceiling: stops clipping when many sounds land together
    const lim = this.ctx.createDynamicsCompressor();
    lim.threshold.value = -12; lim.knee.value = 12; lim.ratio.value = 6;
    this.master.connect(lim).connect(this.ctx.destination);
    this._ambiente();
  },
  applyVolume() {
    if (!this.ctx) return;
    const g = this.on ? this.vol : 0;
    this.master.gain.setTargetAtTime(g, this.ctx.currentTime, .05);
  },
  /** true if the sound can play right now (respecting the minimum interval) */
  _canPlay(key, msMin) {
    if (!this.ctx || !this.on) return false;
    if (this._active > 14) return false;
    const t = performance.now(), u = this._lastAt.get(key) || 0;
    if (t - u < (msMin || 45)) return false;
    this._lastAt.set(key, t);
    return true;
  },

  /* ---- synthesis blocks ---- */
  /** an oscillator with an envelope; f2 sweeps the frequency */
  _tone({ f = 440, f2, kind = 'sine', t = 0, dur = .18, vol = .3, atk = .006, vib, vibF = 6, dest, lp }) {
    const c = this.ctx, t0 = c.currentTime + t;
    const o = c.createOscillator(), g = c.createGain();
    o.type = kind;
    o.frequency.setValueAtTime(f, t0);
    if (f2) o.frequency.exponentialRampToValueAtTime(Math.max(1, f2), t0 + dur);
    if (vib) {  // vibrato: what gives a roar, a moo or a whinny some life
      const lfo = c.createOscillator(), lg = c.createGain();
      lfo.frequency.value = vibF; lg.gain.value = vib;
      lfo.connect(lg).connect(o.frequency); lfo.start(t0); lfo.stop(t0 + dur + .05);
    }
    g.gain.setValueAtTime(0, t0);
    g.gain.linearRampToValueAtTime(vol, t0 + atk);
    g.gain.exponentialRampToValueAtTime(.0001, t0 + dur);
    if (lp) {   // cuts the brightness: what separates "deep and low" from "generically harsh"
      const f = c.createBiquadFilter(); f.type = 'lowpass'; f.frequency.value = lp; f.Q.value = .7;
      o.connect(g).connect(f).connect(dest || this.master);
    } else o.connect(g).connect(dest || this.master);
    o.start(t0); o.stop(t0 + dur + .05);
    this._active++; o.onended = () => this._active--;
  },
  /** a burst of filtered noise: a thud, a brush, a hiss, a puff */
  _noise({ t = 0, dur = .18, vol = .3, kind = 'lowpass', f = 900, f2, Q = 1, dest, lp }) {
    const c = this.ctx, t0 = c.currentTime + t;
    const n = Math.max(1, Math.floor(c.sampleRate * dur));
    const buf = c.createBuffer(1, n, c.sampleRate);
    const d = buf.getChannelData(0);
    for (let i = 0; i < n; i++) d[i] = (Math.random() * 2 - 1);
    const src = c.createBufferSource(); src.buffer = buf;
    const bq = c.createBiquadFilter(); bq.type = kind; bq.Q.value = Q;
    bq.frequency.setValueAtTime(f, t0);
    if (f2) bq.frequency.exponentialRampToValueAtTime(Math.max(20, f2), t0 + dur);
    const g = c.createGain();
    g.gain.setValueAtTime(0, t0);
    g.gain.linearRampToValueAtTime(vol, t0 + .008);
    g.gain.exponentialRampToValueAtTime(.0001, t0 + dur);
    if (lp) {
      const fl = c.createBiquadFilter(); fl.type = 'lowpass'; fl.frequency.value = lp; fl.Q.value = .7;
      src.connect(bq).connect(g).connect(fl).connect(dest || this.master);
    } else src.connect(bq).connect(g).connect(dest || this.master);
    src.start(t0); src.stop(t0 + dur + .02);
    this._active++; src.onended = () => this._active--;
  },
  _chord(freqs, { kind = 'sine', dur = .3, vol = .16, step = .07 } = {}) {
    freqs.forEach((f, i) => this._tone({ f, kind, dur, vol, t: i * step }));
  },

  /* ---- eventos do jogo ---- */
  play(key) {
    switch (key) {
      case 'ui':        if (!this._canPlay(key, 35)) return; this._tone({ f: 880, f2: 1180, dur: .05, vol: .12 }); break;
      case 'tab':       if (!this._canPlay(key, 60)) return; this._tone({ f: 520, f2: 780, dur: .09, vol: .14, kind: 'triangle' }); break;
      case 'open':     if (!this._canPlay(key, 80)) return; this._chord([440, 660], { dur: .16, vol: .1, step: .04 }); break;
      case 'close':    if (!this._canPlay(key, 80)) return; this._chord([660, 440], { dur: .14, vol: .09, step: .04 }); break;
      case 'error':      if (!this._canPlay(key, 180)) return; this._tone({ f: 190, f2: 110, kind: 'square', dur: .17, vol: .16 }); break;
      case 'path':    if (!this._canPlay(key, 55)) return; this._noise({ dur: .07, vol: .16, f: 1600, f2: 500 }); break;
      case 'terrain':   if (!this._canPlay(key, 55)) return; this._noise({ dur: .1, vol: .1, kind: 'bandpass', f: 700, f2: 1500, Q: .7 }); break;
      case 'building':    if (!this._canPlay(key, 90)) return;
        this._noise({ dur: .16, vol: .22, f: 700, f2: 160 }); this._tone({ f: 150, f2: 80, kind: 'triangle', dur: .2, vol: .16 }); break;
      case 'construct': if (!this._canPlay(key, 120)) return;
        this._noise({ dur: .22, vol: .2, f: 1200, f2: 260 });
        this._chord([330, 440, 550], { kind: 'triangle', dur: .28, vol: .12, step: .06 }); break;
      case 'extend':   if (!this._canPlay(key, 120)) return;
        this._noise({ dur: .16, vol: .16, f: 900, f2: 300 });
        this._chord([392, 523], { kind: 'triangle', dur: .24, vol: .12, step: .07 }); break;
      case 'demolish':   if (!this._canPlay(key, 90)) return;
        this._noise({ dur: .3, vol: .26, f: 1800, f2: 120, Q: .6 }); this._tone({ f: 110, f2: 55, kind: 'square', dur: .18, vol: .1 }); break;
      case 'coin':     if (!this._canPlay(key, 70)) return;
        this._tone({ f: 1180, dur: .07, vol: .1 }); this._tone({ f: 1560, dur: .1, vol: .09, t: .05 }); break;
      case 'buy':    if (!this._canPlay(key, 150)) return;
        this._tone({ f: 880, dur: .08, vol: .13 }); this._tone({ f: 1320, dur: .1, vol: .12, t: .07 });
        this._tone({ f: 1760, dur: .16, vol: .1, t: .14 }); break;
      case 'birth': if (!this._canPlay(key, 400)) return;
        this._chord([523, 659, 784, 1046], { kind: 'triangle', dur: .3, vol: .13, step: .09 }); break;
      case 'death':     if (!this._canPlay(key, 400)) return;
        this._chord([392, 330, 262], { kind: 'sine', dur: .5, vol: .13, step: .16 }); break;
      case 'sick':    if (!this._canPlay(key, 400)) return;
        this._tone({ f: 420, f2: 300, kind: 'triangle', dur: .35, vol: .12, vib: 22, vibF: 9 }); break;
      case 'alarm':    if (!this._canPlay(key, 700)) return;
        for (let i = 0; i < 3; i++) {
          this._tone({ f: 780, kind: 'square', dur: .13, vol: .12, t: i * .22 });
          this._tone({ f: 560, kind: 'square', dur: .13, vol: .12, t: i * .22 + .11 });
        } break;
      case 'day':       if (!this._canPlay(key, 900)) return;
        this._chord([523, 784, 1046], { kind: 'sine', dur: .8, vol: .1, step: .11 }); break;
      case 'bills':    if (!this._canPlay(key, 900)) return;
        this._noise({ dur: .3, vol: .12, kind: 'highpass', f: 2600 });
        this._tone({ f: 300, f2: 180, kind: 'triangle', dur: .3, vol: .12, t: .1 }); break;
      case 'bankrupt':  if (!this._canPlay(key, 2000)) return;
        this._chord([330, 262, 196, 131], { kind: 'sawtooth', dur: .9, vol: .12, step: .22 }); break;
    }
  },

  /* ==========================================================================
     VOICES — one "vocal gesture" per family, with per-species exceptions.
     Size pulls the pitch down and the PRNG seeded by the name gives a stable
     detuning, so two species sharing a gesture never sound alike.
     ========================================================================== */
  animalVoice(sp, opts) {
    const espera = (opts && opts.now) ? 0 : 240;
    if (espera && !this._canPlay('voz' + sp.id, espera)) return;
    if (!this.ctx || !this.on) return;
    const dest = (opts && opts.distant) ? this.far : undefined;
    const _t = this._tone, _r = this._noise;
    this._tone = o => _t.call(this, { ...o, dest });
    this._noise = o => _r.call(this, { ...o, dest });
    try {
      const r = mulberry(hashStr(sp.key) + 11);
      const low = 1 / (.45 + Math.min(sp.sizeF, 2.3) * .78);   // bigger = lower
      const dt = 1 + (r() - .5) * .16;                          // a timbre of its own
      const F = f => Math.max(30, f * low * dt);
      const v = (opts && opts.vol) || .22;
      (this['_g_' + gestureOf(sp)] || this._g_grunt).call(this, F, v, r, sp);
    } finally { this._tone = _t; this._noise = _r; }
  },

  /* ---- gestos ---- */
  _g_roar(F, v) {          // lion, tiger, jaguar: low, harmonic and rough
    const f0 = F(115);
    [[1, 1], [2, .42], [3, .2]].forEach(([m, g]) =>
      this._tone({ f: f0 * m, f2: f0 * m * .72, kind: 'sawtooth', dur: .95, vol: v * g * .6,
                  atk: .13, vib: f0 * m * .05, vibF: 27, lp: F(1000) }));  // vibrato = aspereza
    this._noise({ dur: .95, vol: v * .16, kind: 'bandpass', f: F(500), f2: F(190), Q: .8, lp: F(900) });
  },
  _g_meow(F, v) {           // felino pequeno
    this._tone({ f: F(620), f2: F(880), kind: 'sawtooth', dur: .18, vol: v * .8, atk: .03, vib: 24, vibF: 12 });
    this._tone({ f: F(880), f2: F(520), kind: 'sawtooth', dur: .3, vol: v * .7, t: .16, vib: 20, vibF: 10 });
  },
  _g_growl(F, v) {         // bear: lower and more ragged than the roar
    const f0 = F(85);
    [[1, 1], [2, .4], [3, .16]].forEach(([m, g]) =>
      this._tone({ f: f0 * m, f2: f0 * m * .8, kind: 'sawtooth', dur: .8, vol: v * g * .65,
                  atk: .1, vib: f0 * m * .09, vibF: 19, lp: F(750) }));
    this._noise({ dur: .8, vol: v * .18, kind: 'lowpass', f: F(400), f2: F(170), lp: F(700) });
  },
  _g_howl(F, v) {            // lobo: sobe, sustenta, desce — bem tonal
    const a = F(360), b = F(600);
    this._tone({ f: a, f2: b, kind: 'triangle', dur: .45, vol: v * .85, atk: .1, vib: 7, vibF: 5 });
    this._tone({ f: b, dur: .55, vol: v * .8, t: .43, atk: .05, vib: 9, vibF: 5.5 });
    this._tone({ f: b, f2: a * .75, kind: 'triangle', dur: .75, vol: v * .7, t: .96, vib: 12, vibF: 6 });
  },
  _g_bark(F, v, r) {       // fox, wild dog: short bursts
    for (let i = 0; i < 2 + (r() * 2 | 0); i++) {
      this._tone({ f: F(520), f2: F(300), kind: 'sawtooth', dur: .1, vol: v * .9, t: i * .19, atk: .008, vib: 28, vibF: 20 });
      this._noise({ dur: .08, vol: v * .5, kind: 'bandpass', f: 1300, f2: 500, Q: 1, t: i * .19 });
    }
  },
  _g_trumpet(F, v) {        // elephant: metallic, rises and falls, with a rumble under it
    this._tone({ f: F(300), f2: F(640), kind: 'sawtooth', dur: .22, vol: v * 1.1, atk: .02, vib: 16, vibF: 13, lp: 2600 });
    this._tone({ f: F(640), f2: F(360), kind: 'sawtooth', dur: .5, vol: v, t: .2, vib: 26, vibF: 10, lp: 2600 });
    this._tone({ f: F(78), dur: .85, vol: v * 1.1, kind: 'sine', atk: .05 });   // the rumble that gives it its size
  },
  _g_huff(F, v) {            // girafa e okapi: bufo + zumbido grave
    // A giraffe is a near-silent animal: it snorts, it huffs and it emits a
    // ~92 Hz hum. No roar — the "right" answer here is to be discreet.
    this._noise({ dur: .38, vol: v * .8, kind: 'bandpass', f: 1100, f2: 300, Q: .6, lp: 1800 });
    this._tone({ f: F(150), f2: F(96), kind: 'triangle', dur: .34, vol: v * .5, atk: .02, lp: 700 });
    this._tone({ f: 92, dur: 1.3, vol: v * .7, kind: 'sine', atk: .18, t: .16 });  // 92 Hz is a fact about the animal
  },
  _g_bray(F, v) {           // zebra: late em duas partes
    for (let i = 0; i < 2; i++) {
      this._tone({ f: F(430), f2: F(230), kind: 'sawtooth', dur: .17, vol: v, t: i * .28, atk: .01, vib: 34, vibF: 17 });
      this._noise({ dur: .13, vol: v * .4, kind: 'bandpass', f: 800, f2: 340, Q: 1, t: i * .28, lp: 1900 });
    }
  },
  _g_whinny(F, v) {        // cavalo, jumento
    this._tone({ f: F(700), f2: F(300), kind: 'sawtooth', dur: .7, vol: v * .9, atk: .02, vib: 45, vibF: 16 });
    this._noise({ dur: .3, vol: v * .35, kind: 'bandpass', f: 1600, f2: 600, Q: .8, t: .5 });
  },
  _g_moo(F, v) {          // bovine: long, low, a slow undulation
    this._tone({ f: F(190), f2: F(150), kind: 'sawtooth', dur: .95, vol: v * 1.1, atk: .15, vib: 12, vibF: 5.5, lp: F(800) });
    this._tone({ f: F(380), f2: F(300), kind: 'sawtooth', dur: .9, vol: v * .25, atk: .18, vib: 14, vibF: 5.5, lp: F(900) });
  },
  _g_bleat(F, v) {          // antelope, camelid: the fast vibrato of a goat
    this._tone({ f: F(430), f2: F(360), kind: 'sawtooth', dur: .55, vol: v * .9, atk: .04, vib: 40, vibF: 21 });
  },
  _g_call(F, v, r) {        // primata: pant-hoot que acelera e sobe
    const n = 4 + (r() * 3 | 0);
    for (let i = 0; i < n; i++) {
      const k = i / n;
      this._tone({ f: F(480 + k * 420), f2: F(620 + k * 520), kind: 'square',
                  dur: .1, vol: v * (.5 + k * .5), t: i * (.17 - k * .07), atk: .01 });
    }
  },
  _g_chirp(F, v, r) {        // aves: varreduras curtas e agudas
    for (let i = 0; i < 3 + (r() * 3 | 0); i++) {
      const f = F(1900 + r() * 1100);
      this._tone({ f, f2: f * (1.4 + r() * .6), kind: 'sine', dur: .06, vol: v * .55, t: i * .095, atk: .004 });
    }
  },
  _g_squawk(F, v) {        // penguin, goose: harsh pulses
    for (let i = 0; i < 3; i++)
      this._tone({ f: F(400), f2: F(280), kind: 'sawtooth', dur: .17, vol: v * .8, t: i * .21, vib: 38, vibF: 25 });
  },
  _g_hiss(F, v) {          // serpente
    this._noise({ dur: .8, vol: v * .8, kind: 'highpass', f: 3600, f2: 6800, Q: .5 });
  },
  _g_reptile(F, v) {          // lagarto, crocodilo, tartaruga: sopro + ronco
    this._noise({ dur: .5, vol: v * .55, kind: 'bandpass', f: F(760), f2: F(300), Q: 1.3 });
    this._tone({ f: F(105), f2: F(72), kind: 'sawtooth', dur: .45, vol: v * .6, vib: 9, vibF: 13 });
  },
  _g_croak(F, v, r) {        // amphibian: dry pulses
    const n = 4 + (r() * 3 | 0);
    for (let i = 0; i < n; i++)
      this._tone({ f: F(400), kind: 'square', dur: .055, vol: v * .6, t: i * .08, atk: .004 });
  },
  _g_whistle(F, v) {         // golfinho, boto
    this._tone({ f: F(2100), f2: F(3700), kind: 'sine', dur: .15, vol: v * .5, atk: .01 });
    this._tone({ f: F(3500), f2: F(1800), kind: 'sine', dur: .22, vol: v * .45, t: .14 });
    for (let i = 0; i < 5; i++)  // echolocation clicks
      this._tone({ f: 5200, dur: .012, vol: v * .18, t: .36 + i * .035 });
  },
  _g_sealHuff(F, v) {        // seal, sea lion
    for (let i = 0; i < 2; i++)
      this._tone({ f: F(330), f2: F(210), kind: 'sawtooth', dur: .21, vol: v * .85, t: i * .28, vib: 22, vibF: 15 });
  },
  _g_squeak(F, v, r) {      // roedor, morcego, pequenos: agudo e curto
    for (let i = 0; i < 2 + (r() * 2 | 0); i++) {
      const f = F(1500 + r() * 700);
      this._tone({ f, f2: f * .6, kind: 'triangle', dur: .08, vol: v * .5, t: i * .11, atk: .005 });
    }
  },
  _g_buzz(F, v) {         // invertebrados
    this._noise({ dur: .5, vol: v * .35, kind: 'bandpass', f: 4200, Q: 9 });
  },
  _g_grunt(F, v, r) {     // pig, hippo, rhino and the big generics
    const n = 3 + (r() * 2 | 0);
    for (let i = 0; i < n; i++)
      this._tone({ f: F(230), f2: F(160), kind: 'square', dur: .1, vol: v * .7, t: i * .13, atk: .008 });
  },

  /* ---- barramento "distante" ----
     Background animal voices go through here and come out muffled, as if
     from the other side of the park. (The crowd murmur was dropped: noise with
     formants still sounds like wind, not conversation — convincing speech needs
     glottal excitation and a pitch contour, and that is for another day.) */
  _ambiente() {
    const c = this.ctx;
    this.far = c.createGain(); this.far.gain.value = .5;
    const lp = c.createBiquadFilter();
    lp.type = 'lowpass'; lp.frequency.value = 1200; lp.Q.value = .6;
    this.far.connect(lp).connect(this.master);
  },
};
